# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review


- id: 10.48550/arXiv.2606.05975
  type: paper
  description: We introduce T-FunS3D, a task-driven hierarchical open-vocabulary 3D functionality segmentation method that provides actionable perception for robotic applications.
  publisher: IEEE Intl. Conf. on Robotics and Automation (ICRA) 2026
  image: https://t-funs3d.github.io/static/images/T-FunS3D%20teaser.png
  date: 2026-06-01
  buttons:
    - type: paper
      text: PDF
      link: https://arxiv.org/abs/2606.05975v1
    - type: website
      link: https://t-funs3d.github.io/
    - type: source
      text: Github
      link: https://github.com/EdwardjkFeng/T-FunS3D
  tags:
    - Scene Understanding
    - Scene Graph
    - Robotics